id = "faber"
name = "Faber Romanus"
description = "Latin programming language support for Zed."
version = "0.1.0"
schema_version = 1
authors = ["Ian Zepp <ianzepp@gmail.com>"]
repository = "https://github.com/ianzepp/faber"
