id = "faber-romanus"
name = "Faber Romanus"
description = "Latin programming language support"
version = "0.1.0"
schema_version = 1
authors = ["Ian Zepp <ian@ianzepp.com>"]
repository = "https://github.com/ianzepp/faber-romanus"

[grammars.faber_romanus]
repository = "https://github.com/ianzepp/faber-romanus"
rev = "579c98a41421025fdafec9fa46bdc0f73bcac637"
path = "editors/zed/grammars/faber_romanus"
