id = "faber-romanus"
name = "Faber Romanus"
description = "Latin programming language support"
version = "0.1.0"
schema_version = 1
authors = ["Ian Zepp <ian@ianzepp.com>"]
repository = "https://github.com/ianzepp/faber-romanus"

[grammars.faber_romanus]
repository = "https://github.com/ianzepp/faber-romanus"
rev = "223348a5cf2cec5d330951070d301121a4fbd5c2"
path = "editors/zed/grammars/faber_romanus"
